msm:
  # Relative to "data_dir"
  directory: skills
  versioned: true
  repo: {
    # Relative to "data_dir"
    cache: .skills-repo
    url: https://github.com/MycroftAI/mycroft-skills
    branch: 21.02
  }
},
upload_skill_manifest: true
# Directory to look for user skills
directory: ~/.local/share/mycroft/skills
# Enable auto update by msm
auto_update: true
# Enable loading/unloading of skills as files are changed on disk
hot_reload: false
# blacklisted skills to not load
# NB: This is the basename() of the directory where the skill lives, so if
# the skill you want to blacklist is in /opt/mycroft/skills/mycroft-alarm.mycroftai/
# then you should write `["mycroft-alarm.mycroftai"]` below.
blacklisted_skills: []
padatious:
  intent_cache: ~/.local/share/mycroft/intent_cache
  train_delay: 4
  single_thread: false
idle_display_skill: homescreen.mycroftai
